name: tvhproxy
version: '1.0'
summary: A small flask app to proxy requests between Plex Media Server and Tvheadend
description: |
  See https://github.com/morphis/tvhproxy-snap for more details.
confinement: strict
grade: stable

apps:
  tvhproxy:
    command: bin/tvhproxy.sh
    daemon: simple
    plugs: [network, network-bind]

parts:
  common:
    plugin: dump
    source: .
    prime:
      - bin/tvhproxy.sh

  tvhproxy:
    plugin: python
    source: https://github.com/jkaberg/tvhProxy.git
    source-type: git
    requirements: requirements.txt
    install: |
      cp  -R ./ $SNAPCRAFT_PART_INSTALL/opt/tvhproxy
