name: tvhproxy
version: git
summary: A small app to proxy requests between Plex Media Server and Tvheadend
description: |
  See https://github.com/morphis/tvhproxy-snap for more details.
confinement: strict
grade: stable

apps:
  tvhproxy:
    command: bin/tvhproxy.sh
    daemon: simple
    plugs: [network, network-bind]

parts:
  common:
    plugin: dump
    source: bin
    organize:
      tvhproxy.sh: bin/tvhproxy.sh

  tvhproxy:
    plugin: python
    source: https://github.com/jkaberg/tvhProxy.git
    source-type: git
    requirements: requirements.txt
    override-build: |
      snapcraftctl build

      cp tvhProxy.py $SNAPCRAFT_PART_INSTALL
      cp -r templates $SNAPCRAFT_PART_INSTALL
